enableGlobalCache: true
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-berry.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"


packageExtensions:
  "@nestjs/swagger@*":
    dependencies:
      swagger-ui-express: "*"

